### ISSUE TITLE
Privacy checklist

### ISSUE THREAD

**Issue by stefjoosten** [OrdinaNederland/Stichting-NUTwente#509]
Nutwente verwerkt informatie ten behoeve van het plaatsen van Oekraïners bij gastgezinnen in Twente. Dat doet zij in een informatiesysteem voor huisvesting: de productiedatabase. Daarbij verwerkt Nutwente persoonsgegevens. Nutwente wil de privacy van alle personen graag waarborgen en daarom houdt Nutwente zich aan de regels uit de Uitvoeringswet AVG (UAVG). Dit is vertaald in een aantal privacymaatregelen, die in dit issue bijeen zijn gebracht en die gelden voor alle verwerkingen in de productiedatabase. Voor een goed begrip ervan volgt een woordenlijst voor een aantal jargonwoorden.

| Begrip | Definitie |
| --- | --- |
| Aanmelding | het formulier op https://nutwente.azurewebsites.net/GastgezinAanmelding dat het gastgezin invult om zich als gastgezin te laten registreren door Nutwente |
| Active Directory | de voorziening in Azure die de authenticatie van gebruikers verzorgt |
| Buddy | een vrijwilliger die is aangewezen als vaste contactpersoon voor een gastgezin |
| Code Repository | de opslagfaciliteit waarin de broncode van de productiedatabase is opgeslagen |
| Coördinator | een rol die intakes en plaatsingen maakt in de productiedatabase en die in de Active Directory als groep `Coordinator` bekend is |
| Development team | een team dat de productiedatabase beheert, onderhoudt, of vernieuwt |
| Intaker | een vrijwilliger die het intakegesprek met een gastgezin heeft gevoerd |
| Intakeformulier | het formulier op https://nutwente.azurewebsites.net/GastgezinIntake dat het gastgezin invult tijdens het intakegesprek |
| Persoonsgegeven | een gegeven dat in de UAVG als persoonsgegeven is aangemerkt |
| Productiedatabase | de service die op Internet onder de URL `https://nutwente.azurewebsites.net/` toegankelijk is |
| Secretariaat | een rol die gegevens in de productiedatabase kan inzien en die in de Active Directory als groep `Secretariaat` bekend is |
| Superuser | een rol die alles mag in de productiedatabase en die in de Active Directory als groep `Superuser` bekend is |
| Vrijwilliger | een rol die gegevens van gastgezinnen in de productiedatabase verwerkt en die in de Active Directory als groep `Vrijwilliger` bekend is |

# Privacy Principes

- Voor elk verwerkt persoonsgegeven is het doel van de verwerking bekend, zoals bedoeld in de UAVG, zodat de rechtmatigheid inzichtelijk is.
- Als Nutwente een persoonsgegeven verwerkt respecteert Nutwente de zeggenschap van de eigenaar van dat gegeven.
- Een gegeven over een persoon is van die persoon, zodat deze persoon daar zeggenschap over blijft houden. 
- Nutwente beschouwt elke geregistreerde mening of oordeel als persoonsgegeven van de persoon die deze mening of dit oordeel heeft gegeven.
- Toegang tot de productiedatabase is voorbehouden aan personen op basis van "need to know".
- Nutwente spant zich in om onjuiste gegevens zo snel mogelijk te verwijderen of te corrigeren.

# Technische Maatregelen
De volgende vinklijsten verantwoorden met welke technische maatregelen Nutwente zorgt voor privacy in de productiedatabase. Van de afgevinkte items is vastgesteld dat we eraan voldoen. Van de andere maatregelen moet dat nog gebeuren.
## Maatregelen met betrekking tot Doelbinding
- [x] Nutwente verwerkt het e-mail adres en/of telefoonnummer(s) van gastgezinnen om deze gezinnen te kunnen bereiken. 
- [x] Nutwente verwerkt het e-mail adres en/of telefoonnummer(s)  van vrijwilligers om deze mensen te kunnen bereiken.
- [x] Nutwente verwerkt plaatsingsadressen om Oekraïners te kunnen plaatsen en het gastgezin aan de plaatsing te kunnen koppelen.
- [x] Nutwente verwerkt het woonadres van een gastgezin, als dat verschilt van het plaatsingsadres, zodat de buddy zonodig het gastgezin kan bezoeken.
- [x] Nutwente verwerkt gegevens die het plaatsingsadres en het gastgezin beschrijven om een goede match te kunnen maken.
- [x] Nutwente slaat alle aanmeldingen op, zodat er een intaker aan gekoppeld kan worden en deze intaker een intakegesprek kan plannen.
- [x] Nutwente slaat alle ingevulde intakeformulieren op, zodat een coördinator in de toekomst plaatsingen kan verzorgen in dit gastgezin.
- [x] Nutwente koppelt de aanmeldingen en de intakeformulieren aan de juiste gastgezinnen, zodat een gebruiker die toegang heeft tot een gastgezin ook kan zien welke formulieren zijn ingevuld.

## Maatregelen met betrekking tot authenticiteit van gegevens
- [x] Iedere gebruiker maakt zelf een account (of gebruikt een reeds bestaand Microsoft account) bij de productiedatabase, zodat het e-mailadres en telefoonnummer van deze gebruiker door de gebruiker zelf verstrekt is.

## Maatregelen met betrekking tot preventie van datalekken
- [x] Nutwente verwerkt geen onnodige persoonsgegevens, zodat de schade door een eventueel datalek beperkt blijft. Onder onnodig verstaat Nutwente dat het verwerkingsdoel onbekend is of slechts indirect relevant voor het verwerkingsdoel.
- [x] Nutwente verwerkt geen persoonsgegevens van geplaatste personen, zodat een eventueel datalek geen gegevens van geplaatste personen kan opleveren.
- [x] Nutwente verwerkt persoonsgegevens alleen van vrijwilligers die buddy of intaker zijn of zijn geweest, zodat de schade door een eventueel datalek beperkt blijft tot deze personen.
- [x] Een buddy/intaker krijgt alleen toegang tot gegevens van gastgezinnen van wie zij zelf buddy zijn of intaker is of is geweest om datalekken te voorkomen.
- [x] Alleen een Superuser kan de inhoud van de database dumpen naar een spreadsheet, om te garanderen dat de volledige gegevensverzameling bewaard kan worden als de applicatie verhuisd moet worden. Er zijn geen andere datadump functionaliteiten.
- [x] Het development team heeft geen directe toegang tot de database anders dan door de API, zodat er langs directe weg geen datalek vanuit de database kan plaatsvinden.
- [x] In de code repository zijn geen persoonsgegevens aanwezig, zodat het lekken van persoonsgegevens via de code repository ondenkbaar is.
- [x] Het development team beschikt over een dataset met fictieve gegevens voor testdoeleinden, zodat het lekken van authentieke data langs deze weg ondenkbaar is.

## Maatregelen met betrekking tot beveiliging
- [x] Iedere gebruiker maakt zelf een account (of gebruikt een reeds bestaand Microsoft account) bij de productiedatabase, zodat niemand dan de gebruiker zelf het wachtwoord kan weten.
- [x] Een persoon kan alleen gegevens verwerken door ingelogd te zijn in de productiedatabase, behalve wanneer deze persoon zich aanmeldt als gastgezin en/of vrijwilliger, zodat onbevoegden geen toegang kunnen krijgen tot persoonsgegevens in deze database.
- [x] Elk gebruik van de productiedatabase geschiedt via de webservice op `https://nutwente.azurewebsites.net/`, zodat de toegang tot de gegevens gecontroleerd kan plaatsvinden.
- [x] De verwerking van accounts geschiedt in de Active Directory van Azure. Nutwente acht de werkwijze van Azure een voldoende garantie dat degene die op enig tijdstip op dat account inlogt dezelfde persoon is als die zich bij de Active Directory heeft geregistreerd als gebruiker van `nutwente.azurewebsites.net`.
- [x] Een persoon die een account aanmaakt bij de productiedatabase krijgt geen autorisaties, tenzij door tussenkomst van een beheerder, zodat de toegang altijd door een bewust besluit van een persoon is verleend.
- [x] Gastgezinnen krijgen geen toegang tot de database, zodat de kring van gebruikers beperkt blijft.
- [x] In de code repository zijn geen secrets, zoals passwords, aanwezig, die lezers van deze repository ongeoorloofd toegang tot de database kan verschaffen.

## Maatregelen met betrekking tot integriteit van gegevens

- [ ] De productiedatabase bevat een aantal integriteitschecks, zodat de database beheerder de integriteit van de gegevens in de gaten kan houden. #528 , #555 , #669 ,#668 , #670 , #671
- [x] De code van deze applicatie is als code repository beschikbaar op Github als Free Open Source Software, zodat eenieder zich kan vergewissen van de juiste omgang met gegevens.

## Maatregelen met betrekking tot het recht op informatie en het recht op correctie
- [x] Nutwente stuurt een e-mail aan het gastgezin na het indienen van een nieuw aanmeldformulier, om te bevestigen dat de aanmelding is geregistreerd.
- [x] Nutwente stuurt een e-mail aan het gastgezin na het indienen van een nieuw intakeformulier, om te bevestigen dat de aanmelding is geregistreerd.
- [x] De buddy kan in overleg met het gastgezin correcties aanbrengen in de gegevens op de aanmelding en op het intakeformulier.
- [x] Het secretariaat heeft inzage in alle persoonsgegevens in de productiedatabase.
- [x] Elke coördinator kan alle persoonsgegevens inzien en wijzigen.
- [x] Alleen een coördinator kan gastgezinnen verwijderen, 
- [x] Er is een herstelscherm, waar ten onrechte verwijderde gastgezinnen en ten onrechte geregistreerde intakers kunnen worden hersteld.

## Maatregelen met betrekking tot verwijderen, vernietigen en het recht op vergetelheid
- [x] Nutwente verwijdert $^{1}$ op verzoek van een gastgezin alle gegevens inclusief de aanmeldformulieren en intakeformulieren van dat gastgezin.
- [x] De productiedatabase kent een mogelijkheid dat een coördinator kan zien welke gastgezinnen verwijderd zijn, zodat het herstellen van de gegevens tot de mogelijkheden behoort.
- [ ] #517

[1] We maken onderscheid tussen verwijderen en vernietigen. Verwijderde gegevens zijn niet meer zichtbaar, maar wel te herstellen. Vernietigde gegevens zijn onherstelbaar verloren.
